optuna/optuna-integration

.github/workflows/checks.yml, .github/workflows/coverage.yml, .github/workflows/mac-tests.yml, .github/workflows/tests-mpi.yml, README.md, optuna_integration/chainermn.py, pyproject.toml, tests/test_chainermn.py
We have started to move integration modules here. This PR moves the `chainermn` integration module.
- Move `chainermn` integration and its test.
- Fix CI workflow for `chainermn` integration.
=> Move `chainermn` integration

optuna_integration/chainermn.py
This is the follow-up of https://github.com/optuna/optuna/pull/4550
=> update deletion timing of `system_attrs` and `set_system_attr`

.github/workflows/tests.yml, README.md, docs/source/reference/index.rst, optuna_integration/keras.py, pyproject.toml, tests/test_keras.py
Move `integration/keras.py` from optuna/optuna
Move `integration/keras.py` from optuna/optuna
=> Move `integration/keras.py`

.github/workflows/coverage.yml
Coverage.yml is broken. Fix it.
- Delete unnecessary spaces.
- Fix indent level.
=> Fix coverage.yml

docs/source/reference/index.rst
Fix the documentation of Keras
=> Fix Keras docs

pyproject.toml
Same motivation as https://github.com/optuna/optuna/pull/4606.
=> Remove codecov dependencies

README.md
The document of `optuna-integration` built in Read the Docs is available [here](https://optuna-integration.readthedocs.io/en/latest/index.html). This PR set the link in the `README.md`. 
Note that the stable version has not been published since we have no stable release now. It will be available after the stable release.
- Add links of documents
=> Add links of documents

.readthedocs.yml
Due to the release of urllib3 v2.0.2, the build on Read the Docs fails. This PR fixes the build by following https://github.com/optuna/optuna/pull/4659. 
- Fix `.readthedocs.yml` as same as https://github.com/optuna/optuna/pull/4659.
=> Fix the build on Read the Docs by following optuna #4659

.github/workflows/tests.yml, README.md, docs/source/reference/index.rst, optuna_integration/catalyst.py, pyproject.toml, tests/test_catalyst.py
Motivation
Progress https://github.com/optuna/optuna/issues/4484
Description of the changes
- Move `integration/catalyst.py` and its test from `optuna/optuna`.
=> Move `Catalyst`

.github/workflows/tests.yml, optuna_integration/tensorflow.py, tests/test_tensorflow.py
Progress optuna/optuna#4484
- Move `integration/tensorflow.py` and its test from `optuna/optuna`.
=> Move `tensorflow` integration

optuna_integration/version.py
=> Bump up version to 3.2.0b0

optuna_integration/version.py
=> Bump up version number to 3.3.0dev

.github/workflows/coverage.yml, .github/workflows/mac-tests.yml, .github/workflows/tests.yml, README.md, docs/source/reference/index.rst, optuna_integration/mxnet.py, pyproject.toml, tests/allennlp_tests/test_allennlp.py, tests/test_mxnet.py
Progress https://github.com/optuna/optuna/issues/4484 and https://github.com/optuna/optuna/issues/4789. 
Move `MXNetPruningCallback`.
=> Move mxnet

.github/workflows/tests.yml, pyproject.toml
Follow up https://github.com/optuna/optuna/issues/3964
Runs tests in python 3.11 as much as possible
=> Bumpt up python version

optuna_integration/version.py
=> Bump up version number to v3.4.0.dev

README.md
Update the badge as `Python>=3.11` was supported by #34 
Update the shields badge.
=> Update python shield in README.md

setup.cfg
Replace deprecated mypy option.
Replace deprecated option `--strict-concatenate` with `--extra-checks`. See [mypy blog](https://mypy-lang.blogspot.com/2023/08/mypy-15-released.html#:~:text=Deprecated%20Flag) for reference.
=> Replace deprecated mypy option

optuna_integration/version.py
Bump up version to v3.5.0.dev.
=> Bump up version to v3.5.0.dev

.github/workflows/tests.yml
Run `test_tensorflow` in Python v3.11
Update `Test` CI to run `test_tensorflow` even when in Python 3.11
=> Run `test_tensorflow` in Python 3.11

setup.cfg
Fixes the scheduled CI for type checking.
https://github.com/optuna/optuna-integration/actions/runs/6856798590/job/18644673179
Refs #47 
As described in #47, the chainer integration is no longer maintained. In this PR, I made the type checking for chainer integration module excluded.
=> Exclude mypy checks for chainer

README.md, docs/source/reference/index.rst, optuna_integration/fastaiv1.py, optuna_integration/fastaiv2.py, pyproject.toml, tests/test_fastaiv2.py
[#4484 ](https://github.com/optuna/optuna/issues/4484)  partry resolved.
On the Optuna Integration side, I'm working on the fast.ai module .
On the Optuna Integration side, isolation of Optuna integration modules on the fast.ai module.
=> Isolate the fast.ai module from optuna

optuna_integration/version.py
=> Bump up version number to 3.6.0.dev

optuna_integration/mxnet.py
Fix flake8 failure in CI.
Replace `type(xxx) == yyy` structure with `isinstance(xxx, yyy)`.
=> Fix flake8 failure in CI

.github/workflows/mac-tests.yml, .github/workflows/tests.yml
I created the PR #15 to enable CI runs on arbitrary branches. However, this functionality is overly complicated and hasn't been used so far. Therefore, I'm going to delete it.
- Delete workflow dispatch input.
=> Delete workflow dispatch input

.github/workflows/checks.yml, .github/workflows/coverage.yml, .github/workflows/mac-tests.yml, .github/workflows/sphinx-build.yml, .github/workflows/tests.yml, README.md
The default branch of `optuna-integration` is `main`, not `master`.
Fix default branch to `main`.
=> Fix default branch

pyproject.toml
Same as https://github.com/optuna/optuna/pull/5210
=> Not use `black 24.*`

README.md, docs/source/reference/index.rst, optuna_integration/dask.py, pyproject.toml, tests/test_dask.py
Progress https://github.com/optuna/optuna/issues/4484
Move `DaskStorage` into optuna-integration.
=> Move dask integration.

docs/source/reference/index.rst, optuna_integration/__init__.py
- Add the dask integration to `__init__.py`.
- Generate the documentation for the dask integration from `optuna_integration`.
=> Add dask to __init__.py and fix its documentation generation.

.github/ISSUE_TEMPLATE/bug-report.yml, optuna_integration/botorch.py
Fix the documentation and the issue template.
- Replace optuna.integration with optuna_integration in the doc and the issue template.
=> Replace optuna.integration with optuna_integration in the doc and the issue template

.github/workflows/coverage.yml, README.md, docs/source/reference/index.rst, optuna_integration/__init__.py, optuna_integration/cma.py, pyproject.toml, tests/test_cma.py, tests/test_samplers.py
- Progress https://github.com/optuna/optuna/issues/4484.
- Add the pycma integration and the corresponding tests to `optuna_integration`.
=> Migrate pycma integration

README.md, docs/source/reference/index.rst, optuna_integration/__init__.py, optuna_integration/wandb.py, pyproject.toml, tests/test_wandb.py
- Progress https://github.com/optuna/optuna/issues/4484.
- Migrate the wandb integration and the corresponding tests.
=> Migrate the Weights & Biases integration

README.md, docs/source/reference/index.rst, optuna_integration/__init__.py, optuna_integration/mlflow.py, pyproject.toml, tests/test_mlflow.py
- Progress https://github.com/optuna/optuna/issues/4484.
- Add MLflow integration and its tests.
=> Migrate MLflow integration

optuna_integration/__init__.py
Make `from optuna_integration import *` work properly.
- Fix `__all__` in `__init__.py`.
=> Fix __init__.py

pyproject.toml
To fix the CI.
Limit the version of `botorch<0.10.`.
=> Hotfix the version of `botorch<0.10.` for CI failures.

.github/workflows/tests.yml
As the CI fails ([ref](https://github.com/optuna/optuna-integration/actions/runs/8256849149)) since dask v3.0, I added a version constraint.
I added the version constraint of dask in pyproject.toml.
=> Hotfix the CI error by adding version constraint to dask

optuna_integration/version.py
=> Bump up version number to 4.0.0dev

tests/importance_tests/test_init.py, tests/test_botorch.py, tests/test_catboost.py, tests/test_dask.py, tests/test_mlflow.py, tests/test_shap.py, tests/test_sklearn.py, tests/test_tensorboard.py, tests/test_wandb.py
Partially resolve https://github.com/optuna/optuna-integration/issues/107
Put warning filter for Experimental classes, which raises harmless `ExperimentalWarning`s
=> Suppress `ExperimentalWarning`s

.github/workflows/tests.yml
To fix the CI: https://github.com/optuna/optuna-integration/actions/runs/8638933964/job/23684321804
=> Remove dask version constraint

tests/wandb/test_wandb.py
Remove all intended warnings when running `pytest tests/wandb/test_wandb.py`.
Add one more indent block for `track_in_wandb` decorator.
=> Ignore `ExperimentalWarning` for `track_in_wandb`

.github/workflows/checks-and-tests.yml
Rename the CI name from `Checks` to `Checks and Tests`.
=> Rename CI name

README.md
As `README.md` has not been enhanced compared to the modules listed in this package, I will improve the documentation as well here.
=> Enhance `README.md`

optuna_integration/cma/cma.py
As I found an unused module, I removed it.
=> Remove unused module

docs/source/reference/index.rst, optuna_integration/__init__.py, optuna_integration/comet/comet.py, tests/comet/test_comet.py
Followup of https://github.com/optuna/optuna-integration/pull/63.
- Add document section for comet.
- Following style convention of optuna and use inline code block.
=> Add document page and fix docstring and comments

.github/workflows/checks-and-tests.yml
Fix the failed CI. The example of error message is found in https://github.com/optuna/optuna-integration/actions/runs/9769138566.
See the PR title.
=> Add `deprecated` arg for the comet CI job

optuna_integration/version.py
For v4.0.0 beta0 release.
- Bump up version number to 4.0.0b0
=> Bump up version number to 4.0.0b0

tests/lightgbm/test_lightgbm.py
As the CI fails, I fixed the CI.
- Add type ignore as `env.model` is not used in the  test
typing ref: https://lightgbm.readthedocs.io/en/latest/_modules/lightgbm/callback.html
=> Hotfix the CI in LightGBM test

tests/pytorch_lightning/test_pytorch_lightning.py
To fix CI fail, this PR ignores mypy error. This error is caused by the lack of `__all__` in `torch.optim`. See https://github.com/pytorch/pytorch/pull/131959.
- Add `type: ignore` and a TODO comment.
=> Hotfix the mypy error of `test_pytorch_lightning.py`

optuna_integration/cma/cma.py
Follow-up https://github.com/optuna/optuna-integration/pull/116
`optuna_integration.CmaEsSampler` no longer exists, which has caused the link in the PyCmaSampler to break.
Update the docstring of `PyCmaSampler`
=> Follow-up PR 116: Update the docstring of PyCmaSampler

optuna_integration/comet/comet.py
Adding `experimental` decorators will make the class and method more user-friendly by following the convention of other integration classes and methods. 
See title.
=> Add missing experimental decorators to the comet integration

docs/source/_templates/layout.html
I'd like to align the header of the document with the Optuna's document.
This PR is related to https://github.com/optuna/optuna/pull/5595.
- Add Dashboard and OptunaHub and remove Community on the document header.
=> Add Dashboard and OptunaHub links to the document header

optuna_integration/version.py
For release.
Bump up version number to 4.1.0.dev
=> Bump up version number to 4.1.0.dev

README.md
This PR aims to enhance README.md by adding two badges similar to those found in the [Optuna repository](https://github.com/optuna/optuna). These badges will show the latest released versions available on PyPI and Conda Forge.
- Add a badge to display the latest version released on PyPI.
- Add a badge to display the latest version released on Conda Forge.
=> Add badges of PyPI and Conda Forge

optuna_integration/sklearn/sklearn.py
#171  explained. 
If `param_distributions` is `Mapping` other than `dict`, convert it to dict.
Pickling will cause an error if not converted.
=> Accept `Mapping` as `param_distributions` in `OptunaSearchCV`

README.md, docs/source/installation.rst, pyproject.toml
Follow-up https://github.com/optuna/optuna-integration/pull/35 and https://github.com/optuna/optuna-integration/pull/170
* Update badge
* Update classifiers
* Update docs
* Specify `requires-python` in package metadata
=> Update supported Python versions

.github/workflows/sphinx-build.yml
https://github.com/optuna/optuna/issues/5743
Replace v3 with v4. I suppose the [breaking changes](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) do not affect this repo.
=> Update artifact version to v4

optuna_integration/version.py
=> Bump up version number to v4.2.0.dev

.github/workflows/checks_template.yml, optuna_integration/_lightgbm_tuner/optimize.py, optuna_integration/sklearn/sklearn.py
Fix CI failure https://github.com/optuna/optuna-integration/actions/runs/12226044101.
There are several problems.
- Currently, we execute the CI with deprecated modules. This causes an problem like [this](https://github.com/optuna/optuna-integration/actions/runs/12226044101/job/34100786244). We can completely skip the CI with deprecated modules.
- Several non-deprecated modules can install numpy 2.2.0. It causes CI errors. We can fix several lines to fix the errors.
- Skip the CI with deprecated modules.
- Fix several lines.
=> Fix mypy errors due to numpy 2.2.0

pyproject.toml
To fix the CI, this PR adds gPRC libraries to the optional dependencies.
- Install `grpcio` and `protobuf` for tests.
=> Add gRPC libraries to optional dependencies

optuna_integration/version.py
For the next release development
=> Bump up version number to 4.3.0.dev

.github/workflows/sphinx-build.yml, docs/source/conf.py, pyproject.toml
Address https://github.com/optuna/optuna-integration/issues/182 and https://github.com/optuna/optuna/issues/5805.
- Update python 3.12 for sphinx-build 
- Introduce `sphinx-notfound-page`
=> Follow recent changes in `optuna/optuna`'s document sphinx config

docs/source/conf.py, docs/source/reference/index.rst, optuna_integration/botorch/botorch.py, optuna_integration/comet/comet.py, optuna_integration/dask/dask.py, optuna_integration/pytorch_lightning/pytorch_lightning.py, optuna_integration/shap/shap.py, optuna_integration/sklearn/sklearn.py, optuna_integration/tensorboard/tensorboard.py, optuna_integration/wandb/wandb.py
Better documentation links
- A few classes/methods can be linked into third-party docs such as pytorch. 
- Add optuna docs page to `intersphinx_mapping`  to link to optuna/optuna pages.
=> Fix links to external modules

tests/cma/test_cma.py
Fixes https://github.com/optuna/optuna-integration/actions/runs/13424092186/job/37503404806
`UnsupportedDistribution` was removed at Optuna, making tests for PyCmaSampler being failed. This PR remove test cases that depend on `UnsupportedDistribution`.
https://github.com/optuna/optuna/pull/5977
=> Remove test cases that uses UnsupportedDistribution

.github/workflows/checks-and-tests.yml
See https://github.com/optuna/optuna-integration/issues/216
Add a version constraint on xgboost.
=> [hotfix] Add a version constraint on xgboost

optuna_integration/version.py
=> Bump up version number to v4.4.0.dev

optuna_integration/shap/shap.py
As discussed [here](https://github.com/optuna/optuna-examples/pull/320), I have added the example for SHAP in the docstring.
I need some help to correct the docstring formatting.
Could you please review?
cc: @nabenabe0928
=> Add SHAP Example 

.github/workflows/checks_template.yml
=> Pin mypy version to 1.15.*

.pre-commit-config.yaml, CONTRIBUTING.md
This pull request introduces a pre-commit framework to enforce coding standards and streamline code formatting. It includes updates to the `.pre-commit-config.yaml` file for configuring pre-commit hooks and updates to the `CONTRIBUTING.md` file to guide contributors on using the new setup.
- add pre-commit-config.yaml
- add explain of pre-commit command to CONTRIBUTING.md
=> Add pre commit config

optuna_integration/__init__.py
This PR adds `__version__` to directly under `optuna_integration`.
- Enable importing `__version__` from `optuna_integration`
=> Add `__version__` to init
