optuna/optuna-integration

- .github/workflows/pypi-publish.yml
CI fails because the ubuntu version which is used in pypi-publish.yml is old.
- Fix pypi-publish.yml.
> fix pypi publish.yaml

- docs/source/conf.py
Apply the patch in https://github.com/optuna/optuna/pull/4615 to `optuna-integration` docs.
This hotfix will resolve the following issues
- Search results are not shown
- Menu pop-up does not work as expected
- Load `sphinxcontrib.jquery` explicitly.
- Note that this change will be removed after https://github.com/readthedocs/sphinx_rtd_theme/issues/1452 is resolved.
> Load `sphinxcontrib.jquery` explicitly

- .github/workflows/tests.yml
- README.md
- docs/source/reference/index.rst
- optuna_integration/tfkeras.py
- tests/test_tfkeras.py
This PR is a part of https://github.com/optuna/optuna/issues/4484. It isolates the `tf.keras` integration.
Move `optuna/integration/tfkeras.py` to `optuna_integration/tfkeras.py`
> Move `tf.keras` integration

- .github/workflows/tests.yml
- README.md
- docs/source/reference/index.rst
- optuna_integration/skorch.py
- pyproject.toml
- tests/test_skorch.py
Progress https://github.com/optuna/optuna/issues/4484
- Move `integration/skorch.py` and its test from `optuna/optuna`.
> Move skorch

- .github/workflows/tests.yml
With the release of typing-extension v4.6.0, Pydantic now produces an error.
It is fixed in the latest Pydantic (https://github.com/pydantic/pydantic/issues/5821), but we cannot use it because AllenNLP specifies the old spaCy and it specifies the old Pydantic.
- Add a version constraint.
> Fix the CI with AllenNLP

- .github/workflows/coverage.yml
- tests/allennlp_tests/test_allennlp.py
- tests/test_catalyst.py
- tests/test_chainermn.py
- tests/test_keras.py
- tests/test_skorch.py
- tests/test_tensorflow.py
- tests/test_tfkeras.py
Remove unnecessary `pytestmark`s and reduce warnings in the `Tests`
Remove unnecessary `pytestmark`s.
> Remove unnecessary pytestmark

- .github/workflows/tests.yml
The release of tensorboardX v2.6.2 breaks catalyst's CI on Python 3.7. (https://github.com/optuna/optuna-integration/actions/runs/5708836457)
Python 3.7 support for integration module has been dropped. This PR reflects it to the CI on this repository.
ref: https://github.com/optuna/optuna/issues/4586, https://github.com/optuna/optuna/pull/4784
Remove Python 3.7 from Tests CI.
> Drop Python 3.7 support

- optuna_integration/allennlp/_dump_best_config.py
- optuna_integration/allennlp/_executor.py
- optuna_integration/allennlp/_pruner.py
- optuna_integration/chainer.py
- optuna_integration/chainermn.py
The tests of allennlp and chainer integrations were deleted. This PR adds the deprecated decorator to those integrations.
Deprecate allennlp and chainer integrations
> Deprecate allennlp and chainer integrations

- .github/workflows/tests.yml
This PR aims to reduce the runtime of tests at each PR push.
The changes made here are based on [PR#5067](https://github.com/optuna/optuna/pull/5067) in Optuna.
The changes are as follows:
1. add a dynamic workflow matrix for each test, and
2. remove non-oldest and non-latest Python versions from each test.
> Remove non oldest and latest Python versions from tests

- README.md
- docs/source/reference/index.rst
- optuna_integration/tensorboard.py
- pyproject.toml
- tests/test_tensorboard.py
Progress optuna/optuna#4484  
**Description of the changes** 
Move integration/tensorboard.py and its test from optuna/optuna
> Move Tensorboard Integration

- .coveragerc
- .github/workflows/coverage.yml
The test coverage is not correctly calculated because of the wrong source path.
- Fix the source path to `optuna_integration` from `optuna`.
> Fix coverage source path

- README.md
- docs/source/reference/index.rst
- optuna_integration/catboost.py
- pyproject.toml
- tests/test_catboost.py
- Progress https://github.com/optuna/optuna/issues/4484
- Add optuna/integration/catboost.py and its test from optuna/optuna to optuna-integration for isolation of the CatBoost integration
> Add CatBoost integration

- tests/importance_tests/test_init.py
In `importance_test`, there is an unused and potentially unintended import from `optuna.integration`, which should be `ooptuna_integration`.
Remove `import optuna.integration.shap` as it is not used.
> Fix unused (and unintended) import

- README.md
- docs/source/reference/index.rst
- optuna_integration/__init__.py
- optuna_integration/shap.py
- optuna_integration/sklearn.py
- pyproject.toml
- tests/test_sklearn.py
- Progress https://github.com/optuna/optuna/issues/4484
- Add optuna/integration/sklearn.py and its test from optuna/optuna to optuna-integration for isolation of the sklearn integration.
- Resolve https://github.com/optuna/optuna/issues/5206
In this PR, I apply some changes required to migrate the sklearn integration as follows.
- Introduce the lazy import of modules [the same way as optuna.integration](https://github.com/optuna/optuna/blob/master/optuna/integration/__init__.py).
- This allows us to lazily import `optuna_integration.OptunaSearchCV` and other modules.
- Make API references correctly generated from `optuna_integration`, not `optuna.integration` (the current reference generation has an inappropriate cycle dependency, i.e., the documents for `optuna_integraiton` are …
> Add sklearn integration

- docs/source/reference/index.rst
- Generate the Tensorflow doc from `optuna_integration` rather than `optuna.integration`.
> Fix the doc for TensorFlow

- pyproject.toml
- Add `scikit-optimize` to `pyroject.toml` because it is a dependency for the skopt integration.
- This is a follow-up task for https://github.com/optuna/optuna-integration/pull/74.
> Add skopt dependency

- formats.sh
As formatting is one of the requirements of PRs to be merged, I would like to add formats.sh so that external contributors can easily verify how to fix their modifications.
I added format.sh based on the optuna master  branch. 
The only change I made from the optuna master branch is here:
[The corresponding lines](https://github.com/optuna/optuna/blob/master/formats.sh#L45-L46)
> Add formats.sh based on optuna/master

- optuna_integration/xgboost.py
Fix CI failure in `optuna/example`. See https://github.com/optuna/optuna-examples/actions/runs/7845757202
Fix wrong import path to `try_import()`, which was brought by https://github.com/optuna/optuna-integration/pull/65. 
`with open optuna_integration._imports.try_import() as _imports:` fails since `optuna_integration._imports` and `_imports` causes name collision (cf. [PEP343](https://peps.python.org/pep-0343/#specification-the-with-statement))
See https://github.com/Alnusjaponica/optuna-examples/pull/3 for the outcome.
> Fix import path

- README.md
> Fastai readme fix

- optuna_integration/_lightgbm_tuner/optimize.py
- optuna_integration/chainermn.py
- optuna_integration/dask.py
- optuna_integration/pytorch_distributed.py
- pyproject.toml
Same as https://github.com/optuna/optuna/pull/5252
Same as https://github.com/optuna/optuna/pull/5252
> Apply Black 2024 to codebase

- tests/lightgbm_tuner_tests/test_optimize.py
I find that [tests/lightgbm_tuner_tests/test_optimize.py is corrupted](https://github.com/optuna/optuna-integration/actions/runs/7926284858/job/21640839531?pr=88).
This PR fixes the error in the test.
> Fix lightgbmtuner test.

- optuna_integration/botorch.py
- pyproject.toml
Resolve #97.
Revert https://github.com/optuna/optuna-integration/pull/96 and pass two arguments to `ConstrainedMCObjective`'s `forward` that should take two arguments since v0.10.0 by https://github.com/pytorch/botorch/pull/2199 and older botorch supports both one and two arguments.
> Pass two arguments to the forward of `ConstrainedMCObjective` to support `botorch=0.10.0`

- .github/workflows/checks.yml
- .github/workflows/tests-mpi.yml
The latest `pipdeptree`, v2.17.0, fails to parse version constraints.
https://github.com/optuna/optuna-integration/actions/runs/8562392755/job/23465560814
Note: I think that the cause of this error is the incorrect format of `catalyst`.
https://github.com/catalyst-team/catalyst/blob/v22.04/requirements/requirements-cv.txt#L3
Install `pipdeptree` v2.16.2 in CIs.
> Install `pipdeptree` v2.16.2 to hotfix parse error

- optuna_integration/mlflow.py
- tests/test_mlflow.py
The strategy for infering the run name was not aligned between the base class `MLflowCallback` and the decorator `track_in_mlflow`. 
* in MLflowCallback we take the run name given by the user and we fallback to trial number if not given : https://github.com/optuna/optuna-integration/blob/main/optuna_integration/mlflow.py#L149 
* in decorator we take by default trial.number: https://github.com/optuna/optuna-integration/blob/main/optuna_integration/mlflow.py#L211 
This PR aligned the strategy to get the run name from MLfowCallback and pass it to mlflow. We lookup `_mlflow_kwargs` and we fallback on trial.number if not given.
> Align run name strategy between MLflowCallback and track_in_mlflow method

- docs/source/reference/index.rst
- optuna_integration/__init__.py
- optuna_integration/cma/__init__.py
- optuna_integration/cma/cma.py
- tests/cma/test_cma.py
I want to remove deprecated `CmaEsSampler` from integration. This PR does not affect `optuna/sampler/_cmaes.py`.
This PR is related to PR https://github.com/optuna/optuna/pull/1325 and https://github.com/optuna/optuna/pull/5417 .
I removed `CmaEsSampler` from integration.
> Remove deprecated `CmaEsSampler` from integration

- optuna_integration/botorch/botorch.py
- tests/botorch/test_botorch.py
Fixes `BoTorchSampler` when using `qnei_candidates_func` on problems with constraints.
Applies the same fix in #106 to `qnei_candidates_func` (it seems that this candidate function was missed).
Also updates the tests to include `qnei_candidates_func`, which would have caught this bug.
> Pass two arguments to the forward of `ConstrainedMCObjective` in `qnei_candidates_func`

- pyproject.toml
Follow-up https://github.com/optuna/optuna-integration/pull/39
`optuna-integrations` already supports Python 3.11. However, it's not listed in PyPI classifiers.
> Update PyPI classifiers for Python 3.11 support

- optuna_integration/sklearn/sklearn.py
- tests/sklearn/test_sklearn.py
Using sklearn's CV splitter which results in a single split, e.g. `PredefinedSplit`, causes `OptunaSearchCV` to fail to report the test scores. The reported scores are used for the default implementation of the `TerminatorCallback`. However, the error is raised irrespective of the presence of this callback. As a result, the `OptunaSearchCV` is unnecessarily unusable when a single split CV is provided and no callback relies on reported scores.
Instead of raising the ValueError in `OptunaSearchCV`, which interrupts the fit, a warning is raised, explaining the problem to the user and forwarding the error message. It is up to the user to decide whether action is required and the fit continues on default. If this causes errors downstream, the warning should aid the user in understanding and …
> Allow single split cv in `OptunaSearchCV`

- optuna_integration/comet/comet.py
- tests/comet/test_comet.py
As the comet integration has not followed the Optuna convention, I applied the formatter.
- Apply formatter
- Use `__future__.annotations`
> Apply formatter and follow the Optuna conventions

- optuna_integration/_lightgbm_tuner/_train.py
- optuna_integration/_lightgbm_tuner/optimize.py
- tests/lightgbm/test_optimize.py
As the verbosity of `LightGBMTuner` is deprecated, I removed the argument.
- Remove the `verbosity` argument
> Remove verbosity of `LightGBMTuner`

- optuna_integration/__init__.py
- optuna_integration/_lightgbm_tuner/_train.py
- optuna_integration/_lightgbm_tuner/optimize.py
- tests/lightgbm/test_optimize.py
As `verbosity`, which is a positional arg, was removed from LightGBM tuner and it slides the positional arg order, I made args after `verbosity` as keyword args only.
- Move the location of `*`
> Move positional args of LightGBM tuner

- optuna_integration/botorch/botorch.py
- tests/botorch/test_botorch.py
Improves the way constraints are handled by the BoTorch sampler.
Updates the candidates functions to pass the constraints directly to the acquisition function as was introduced in pytorch/botorch#1791. This can improve performance, by less harshly penalising infeasible solutions which may lead to an overall improvement, as well as avoid numerical problems.
> Update BoTorch samplers to support new constraints interface

- tests/lightgbm/test_optimize.py
- tests/sklearn/test_sklearn.py
A few lines in test files have E721 errors detected by `ruff`.
Fixes them.
> Fix E721 errors

- optuna_integration/botorch/botorch.py
This  is a followup of:
- https://github.com/optuna/optuna-integration/pull/132
- Refactor the message
- Separate constraint funcs
> Refactor botorch

- pyproject.toml
- Similar to https://github.com/optuna/optuna/pull/5645
Currently, the license was shown in PyPI as follows:
- Remove duplicated license definition
> Remove duplicated license definition.

- optuna_integration/sklearn/sklearn.py
- tests/sklearn/test_sklearn.py
To allow for catching exceptions during fit, an init param for "catch" is added, which is passed to self.study_.optimize
`catch` was previously not passed to `self.study_.optimize`, meaning that there was no way to catch exceptions at fit time (see issue: https://github.com/optuna/optuna-integration/issues/162
Simply adding an init parameter called `catch`, which is then passed to `self.study_.optimize`
> Update sklearn.py by addind catch to OptunaSearchCV

- .github/workflows/checks-and-tests.yml
- .github/workflows/checks_template.yml
The latest fastai requires numpy >= 2.0 that does not work on Python < 3.9.
This PR disables the fastai CI for Python < 3.9.
> Fix CI for fastaiv2

- optuna_integration/sklearn/sklearn.py
This PR fixes errors after upgrading mypy v1.12.0.
- Avoid passing an invalid type variable to `np.unique` in `sklearn.py`.
> Fix for mypy

- optuna_integration/mlflow/mlflow.py
- tests/mlflow/test_mlflow.py
This PR fixes CI errors in the mlflow integration.
- Add an explicit conversion to bool.
- Increase `len(my_user_attr)` limit to 8000 following the change of mlflow (https://github.com/mlflow/mlflow/commit/da8a91edb8843e1161702c00be45a5937c8272f0).
- Set "type: ignore" in L130 to avoid error due to an invalid type hint in https://github.com/mlflow/mlflow/blob/0862ba2c42263e11f6058a73d4ff2b885f176241/mlflow/tracking/client.py#L2969-L2980 (experiment_ids: List of experiment IDs, or a single int or string id but its type hint is List[str]).
> Fix mlflow integration for CI

- optuna_integration/sklearn/sklearn.py
#173  explained.
Re-define some property (`predict` and related one) as method.
- Optuna version:3.5.0
- Optuna Integration version:3.5.0
- Python version:3.11.6
- OS:macOS-14.7-arm64-arm-64bit
- scikit-learn version: 1.4.0
I've tested locally as follows;
```python
import optuna
from sklearn.cross_decomposition import PLSRegression
from sklearn.datasets import make_regression
from sklearn.model_selection import cross_val_predict
X, y = make_regression(n_samples=100, n_features=10, bias=1, random_state=334)
ocv = optuna.integration.OptunaSearchCV(
PLSRegression(),
param_distributions=dict(n_components=optuna.distributions.IntDistribution(1, 10)),
cv=5,
)
y_oof = cross_val_predict(ocv, X, y, cv=5)
```
and,
```python
import optuna
from sklearn.tree import DecisionTreeClassifier
from …
```
> Allow use of `OptunaSearchCV` with `cross_val_predict`.

- .github/workflows/pypi-publish.yml
Refs https://github.com/optuna/optuna/pull/5759
This PR bypasses a twine's bug by turning off release attestations. Please see the below issue and a PR for details.
* https://github.com/pypa/gh-action-pypi-publish/issues/283
* https://github.com/langchain-ai/langchain/pull/27765
> Fix a GitHub action workflow for publishing to PyPI

- .github/workflows/checks-and-tests.yml
- optuna_integration/skorch/__init__.py
This PR is to fix the CI.
- Add version constraint
- Add a TODO comment to remove this version constraint once the new version of scikit-learn is released.
Additional Reference
- https://github.com/uber/causalml/issues/808
> Fix CI by adding a version constraint

- pyproject.toml
Hi.
I just noticed renovate bot does not paste the release note to the PR for optuna-integration, while it does to one for optuna. I suspect that the reason is the missing repository URL in pyproject.toml.
Added `project.urls.repository` field of pyproject.toml.
> Set repository url

- .github/workflows/checks_template.yml
- optuna_integration/botorch/botorch.py
- optuna_integration/comet/comet.py
Add flake8 in CI, which is accidently deleted in [#98 ](https://github.com/optuna/optuna-integration/pull/98)
- Add flake8 in `.github/workflows/check_template.yml`
- Make it to Ignore errors in some files
- The issue is filed here: [Fix Flake8 Errors in CI #202](https://github.com/optuna/optuna-integration/issues/202)
> Add flake8 in ci

- optuna_integration/_lightgbm_tuner/_train.py
- optuna_integration/_lightgbm_tuner/optimize.py
- optuna_integration/lightgbm/lightgbm.py
- tests/lightgbm/test_lightgbm.py
Makes two changes to let `optuna-integration[lightgbm]` be compatible with the latest release of lightgbm, 4.6.0.
Attempts to resolve issue [204](https://github.com/optuna/optuna-integration/pull/204) 
[Here](https://github.com/microsoft/LightGBM/compare/v4.5.0...v4.6.0#) is a link to the diff between lightgbm 4.5.0 (works with optuna-integration[lightgbm]) and 4.6.0 (does not work).
The breaking changes are in these two PRs:
- [#6706](https://github.com/microsoft/LightGBM/pull/6706). The fix for this is straightforard.
-  [#6761](https://github.com/microsoft/LightGBM/pull/6761). I'm less sure about my fix to address this change.
1. The `feature_name` and `categorical_feature` arguments to `lgb.train` and `lgb.cv` were removed in LightGBM …
> [fix] lgbm 4.6.0 compatibility

- optuna_integration/_lightgbm_tuner/optimize.py
With Numpy=2.2.4, mypy raises following errors.
https://github.com/optuna/optuna-integration/actions/runs/13935185091/job/39001498800
```
$ mypy optuna_integration/_lightgbm_tuner/
Success: no issues found in 5 source files
$ pip install -U numpy
Requirement already satisfied: numpy in ./venv/lib/python3.11/site-packages (2.1.3)
Collecting numpy
Downloading numpy-2.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Downloading numpy-2.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 84.9 MB/s eta 0:00:00
Installing collected packages: numpy
Attempting uninstall: numpy
Found existing installation: numpy 2.1.3
Uninstalling numpy-2.1.3:
Successfully uninstalled numpy-2.1.3
Successfully …
```
> Fix a mypy error when using numpy>=2.2.4

- optuna_integration/dask/dask.py
- tests/dask/test_dask.py
Fixes #211 
When copying the storage from the cluster to local, the storage itself was serialized and transferred, but the SQLite DB file referenced by `RDBStorage` was not included. This caused issues like the one in issue #211.  
By converting the storage to `InMemoryStorage` on the cluster side before copying, the process now works correctly.
> Convert storage into `InMemoryStorage` before copying to the local

- optuna_integration/_lightgbm_tuner/optimize.py
Follow-up https://github.com/optuna/optuna-integration/pull/212
After merging #212, CI workflows in optuna-integration and optuna-examples became being failed as shown below:
* https://github.com/optuna/optuna-examples/actions/runs/13972510681/job/39117782817
* https://github.com/optuna/optuna-integration/actions/runs/13981048377/job/39146195912
Use `typing.List` instead of `list` for Python 3.8 users.
> Fix a bug of lightgbm tuner for Python 3.8 users

- optuna_integration/cma/cma.py
As discussed [here](https://github.com/optuna/optuna-examples/pull/321), I have added the example for pycma in the docstring.
I need some help to correct the docstring formatting.
Could you please review?
cc: @nabenabe0928
> Add Pycma Example

- optuna_integration/botorch/botorch.py
- pyproject.toml
I'm getting warnings when running a study with > 1 objectives and no constraints. The warnings say that I should just replace the method with the log version, and there's no reason not to do so.
For more info, see: https://github.com/pytorch/botorch/blob/main/botorch/exceptions/warnings.py#L68
Use the qLogExpectedHypervolumeImprovement instead of qExpectedHypervolumeImprovement
> Fix numerical issue warning on `qehvi_candidates_func`
